### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by ShiftyOG** [michael86/esx_cad#1] opened 2019-08-22 23:21 UTC
1) I changed the database entry and I modified the vehicle script to also add ownerName. But in the database it still shows up as NULL.
 
RegisterNetEvent('VehicleShop:CompletePurchase')
AddEventHandler('VehicleShop:CompletePurchase', function(vehicleProps)
	local xPlayer = ESX.GetPlayerFromId(source)
	local name = GetCharacterName(source)
	while not xPlayer do Citizen.Wait(0); xPlayer = ESX.GetPlayerFromId(source); end

  MySQL.Async.execute('INSERT INTO owned_vehicles (owner, plate, vehicle) VALUES (@owner, @plate, @vehicle)',
  {
    ['@owner']   = xPlayer.identifier,
    ['@plate']   = vehicleProps.plate,
    ['@vehicle'] = json.encode(vehicleProps),
	['@ownerName'] = name
  })
end)

function GetCharacterName(source)
    local result =
    MySQL.Sync.fetchAll(
    'SELECT firstname, lastname FROM users WHERE identifier = @identifier',
    {
        ['@identifier'] = GetPlayerIdentifiers(source)[1]
    })
    
    if result[1] and result[1].firstname and result[1].lastname then
        return ('%s %s'):format(result[1].firstname, result[1].lastname)
    end
end

2) I cannot close the CAD. I tried adding a new thread when I press backspace it should close but it does not. Do you know how to close it?

**Comment by michael86** [comment] 2019-08-22 23:26
So teh esx_vehicleshop change will only add the character name for vehicles that are purchased after the change, if you already have a playerbase, then you will have to manually add there names, or create a sql query to update them.

You shouldn't have to create a new thread to close it. There's a function in the js that closes the gui when you press escape: 
```js
//ON DOCUMENT READY
$(document).ready(function () {

    $("body").on("keyup", function (key) { //allow escape to be used to close the cad. 
        if (key.which == 27) {
            exit();
        }
    });

});
```

**Comment by ShiftyOG** [comment] 2019-08-22 23:34
It is only on my dev server. Every car I purchase does not add a name. Also i tried pressing escape but it did nothing does it work fine for you?

**Comment by michael86** [comment] 2019-08-22 23:38
Re the name, is there any error in the server console of f8 console? 

And yeah, escape works fine for me. Could you try downloading the latest version and try that please. There's other people in a discord I'm in that are also testing it and one other person had the same problem. Escape wasn't working! They updated it to the latest version and that seemed to fix it.

**Comment by michael86** [comment] 2019-08-22 23:50
Also I've just noticed in your sql, if that's literally what you have in the file, you've not added it properly. 

you have
```sql
MySQL.Async.execute('INSERT INTO owned_vehicles (owner, plate, vehicle) VALUES (@owner, @plate, @Vehicle)',
{
        ['@owner'] = xPlayer.identifier,
        ['@plate'] = vehicleProps.plate,
        ['@Vehicle'] = json.encode(vehicleProps),
        ['@ownerName'] = name
})
end)
````

You need to add the ownerName to the actual query

```sql
MySQL.Async.execute('INSERT INTO owned_vehicles (owner, plate, vehicle, ownerName) VALUES (@owner, @plate, @Vehicle, @ownerName)',
{
          ['@owner'] = xPlayer.identifier,
          ['@plate'] = vehicleProps.plate,
          ['@Vehicle'] = json.encode(vehicleProps),
          ['@ownerName'] = name
})
end)
```

**Comment by ShiftyOG** [comment] 2019-08-22 23:51
Ill try that now, Is this discord public? Could I get an invite?

**Comment by michael86** [comment] 2019-08-22 23:51
https://discord.gg/NnZNBk

**Comment by michael86** [comment] 2019-08-22 23:57
Let me know if the sql change worked for you as well as updateing the resource fixing the escape please.

**Comment by ShiftyOG** [comment] 2019-08-23 00:02
Ill look at the sql change, by the way the invite did not work add me Shifty#6424

**Comment by JiminyKroket** [comment] 2019-08-23 00:04
"This is a dev release and is not a simple plug and play resource. You will need to make changes to your resources to make this work the way it is intended and I will not be providing support to help you get it working with your server.' Exactly from the README

**Comment by michael86** [comment] 2019-08-23 00:09
https://discord.gg/vufg5Ab Try that, I just tested the link and worked for me 🤷‍♂

**Comment by Mamafeinn** [comment] 2019-08-23 15:45
Hey, Im also having an issue, where i cant search for existing players, they are registered automatically on the Cad_Users, but i cant search for them, it's registering them there as steam:(steam id)... but your test subjects are saved as Char1:(steam id)

**Comment by michael86** [comment] 2019-08-23 16:30
char has nothing to do with it, that's part of esx_kashacters. What's the format for dob? Should be dd/mm/yyyy if it is like that, then you've done something wrong.

**Closed** 2019-08-24 10:28 UTC

**Comment by Mamafeinn** [comment] 2019-08-24 11:15
ofcourse i'm doing the date right.. Everything works perfectly, it's just searching for chars that's it

**Comment by michael86** [comment] 2019-08-24 11:23
Well like I said, you've got to be doing something wrong as character searching is working for everyone else that is testing it. Try deleting the tables, and resource, then install it again. Also, unless I can reproduce the error, I can't fix it.
